# -*- coding: utf-8 -*-
"""estimatedPi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mnonlBW_jL-OhfAdk_0OIWnIrpnjSjn2
"""

import math
import random
import matplotlib.pyplot as plt

random.seed(1)


N = 10000
hit = 0

r_pi = []
plt.figure(figsize=(6,6))
# Square
plt.plot([0,5,5,0,0], [0,0,5,5,0], c='blue')
# Arc
interval = 3/1000
ax = []
ay = []
for i in range(0, 1001):
    x = i*interval
    ax.append(x)
    y = math.sqrt(9-x*x)
    ay.append(y)

plt.plot(ax, ay, c='red')


hx = []
hy = []

mx = []
my = []

for i in range(1, N+1):
    x = random.uniform(0,5)
    y = random.uniform(0,5)
    
    if x <= 3 and y <= math.sqrt(9-x*x):
        hit += 1
        hx.append(x)
        hy.append(y)
    else:
        mx.append(x)
        my.append(y)
    if(i in [100,1000,10000]):
        r_pi.append((hit*4*25)/(N*9))
    

plt.scatter(hx, hy, c='red',s=5)
plt.scatter(mx, my, c='blue',s=5)
est_pi = (hit*4*25)/(N*9)

#Estimated value of PI
print(est_pi)

#Estimated value of the area of the circle.
for i in r_pi:
  print(4*i*3*3)

print(r_pi)

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
trials = ['100','1000','10000']
ax.bar(trials,bar_pi)
plt.show()